ci: fix daily-validator-build
There is an error when vector-store and validator binaries are already built:

```
Run cp scripts/run-validator-with-scylla-docker .
cp: cannot stat 'scripts/run-validator-with-scylla-docker': No such file or directory
Error: Process completed with exit code 1.
```

The reason is that repository is not cloned locally. The commit fixes this by
removing condition on checkout step.

Fixes: VECTOR-586